# Metrics Executor — Test Notebook NEEDS UPDATING TO ACCOUNT FOR NFLREADPY

This notebook validates `metrics_executor.py` end-to-end on the 2025 regular season PBP data.


1. Import libraries & the executor
2. Load & clean PBP (same logic as your main notebook)
3. Run smoke tests & display outputs

In [1]:
# Auto-reload so edits to metrics_executor.py are picked up
%load_ext autoreload
%autoreload 2

In [2]:
import polars as pl
import nfl_data_py as nfl
from metrics_executor import MetricsExecutor
print('Libraries imported. Ready to load data.')

Libraries imported. Ready to load data.

### **Load and Clean Data**

In [3]:
# --- Clean 2025 Play-by-Play Data using Polars ---

# Load 2025 play-by-play data
df_twofive = pl.from_pandas(
    nfl.import_pbp_data(
        [2025],
        downcast=True,
        cache=False,
        alt_path=None,
        include_participation=False
    )
)

# Keep only regular season plays
df_twofive = df_twofive.filter(pl.col("season_type") == "REG")

# Normalize pass/rush flags
df_twofive = df_twofive.with_columns([
    pl.col("pass").fill_null(0).cast(pl.Int8).alias("pass"),
    pl.col("rush").fill_null(0).cast(pl.Int8).alias("rush"),
])

# Overwrite play_type pass/run if flagged, else keep original
#     Also handle any numeric or null values 
df_twofive = df_twofive.with_columns(
    pl.when(pl.col("pass") == 1).then(pl.lit("pass"))
     .when(pl.col("rush") == 1).then(pl.lit("run"))
     .otherwise(
         pl.col("play_type")
           .cast(pl.Utf8)
           .fill_null("no_play")
           .replace({"0": "no_play", "0.0": "no_play"})
     )
     .alias("play_type")
)

#Clean up whitespace / case for consistency
df_twofive = df_twofive.with_columns(
    pl.col("play_type").str.strip_chars().str.to_lowercase()
)

2025 done.
Downcasting floats.

## Test Data Cleaning

#Checking that plays include epa, null values are handled, etc

In [4]:
# --- Clean 2025 Play-by-Play Data using Polars ---

# 1️⃣ Load 2025 play-by-play data
df_twofive = pl.from_pandas(
    nfl.import_pbp_data(
        [2025],
        downcast=True,
        cache=False,
        alt_path=None,
        include_participation=False
    )
)

# 2️⃣ Keep only regular season plays
df_twofive = df_twofive.filter(pl.col("season_type") == "REG")

# 3️⃣ Normalize pass/rush flags (handle nulls, enforce integer dtype)
df_twofive = df_twofive.with_columns([
    pl.col("pass").fill_null(0).cast(pl.Int8).alias("pass"),
    pl.col("rush").fill_null(0).cast(pl.Int8).alias("rush"),
])

# 4️⃣ Overwrite play_type like pandas: pass/run if flagged, else keep original
#     Also handle any numeric or null values safely.
df_twofive = df_twofive.with_columns(
    pl.when(pl.col("pass") == 1).then(pl.lit("pass"))
     .when(pl.col("rush") == 1).then(pl.lit("run"))
     .otherwise(
         pl.col("play_type")
           .cast(pl.Utf8)
           .fill_null("no_play")
           .replace({"0": "no_play", "0.0": "no_play"})
     )
     .alias("play_type")
)

# 5️⃣ (Optional) Clean up whitespace / case for consistency
df_twofive = df_twofive.with_columns(
    pl.col("play_type").str.strip_chars().str.to_lowercase()
)

# 6️⃣ Final sanity check
print("Rows total:", df_twofive.height)
print("Unique play types:", df_twofive.select(pl.col("play_type").unique()).to_series().to_list())
print("Null EPA:", df_twofive.select(pl.col("epa").null_count()).item())

# 7️⃣ Preview value counts like pandas
df_twofive.select(pl.col("play_type").value_counts()).to_pandas()

2025 done.
Downcasting floats.
Rows total: 16193
Unique play types: ['pass', 'kickoff', 'no_play', 'extra_point', 'punt', 'qb_spike', 'field_goal', 'qb_kneel', 'run']
Null EPA: 188

                                    play_type
0     {'play_type': 'qb_kneel', 'count': 158}
1         {'play_type': 'punt', 'count': 677}
2      {'play_type': 'qb_spike', 'count': 34}
3         {'play_type': 'run', 'count': 4510}
4   {'play_type': 'field_goal', 'count': 395}
5     {'play_type': 'no_play', 'count': 1593}
6  {'play_type': 'extra_point', 'count': 438}
7        {'play_type': 'pass', 'count': 7420}
8      {'play_type': 'kickoff', 'count': 968}

In [5]:
#check play type totals

df_twofive.select(pl.col("play_type").value_counts()).to_pandas()

                                    play_type
0     {'play_type': 'no_play', 'count': 1593}
1   {'play_type': 'field_goal', 'count': 395}
2         {'play_type': 'punt', 'count': 677}
3     {'play_type': 'qb_kneel', 'count': 158}
4      {'play_type': 'qb_spike', 'count': 34}
5  {'play_type': 'extra_point', 'count': 438}
6        {'play_type': 'pass', 'count': 7420}
7         {'play_type': 'run', 'count': 4510}
8      {'play_type': 'kickoff', 'count': 968}

In [6]:
mex = MetricsExecutor(df_twofive)

print(
    mex.df
      .select(pl.col("play_type").value_counts().alias("vc"))
      .unnest("vc")
      .sort("play_type")
)
# Expect play_type values like: "pass", "rush", (maybe None), and special teams if you didn't drop them

df_rush = mex._filter_kind(mex.df, "rush")
print("rush rows:", df_rush.height)

shape: (3, 2)
┌───────────┬───────┐
│ play_type ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ null      ┆ 4263  │
│ pass      ┆ 7420  │
│ rush      ┆ 4510  │
└───────────┴───────┘
rush rows: 4510

In [7]:
# --- Compare counts via Pandas vs Polars to ensure consistency ---
import polars as pl

# --- Polars value counts ---
vc_pl = (
    df_twofive
    .select(pl.col("season_type").value_counts().alias("vc"))  # returns a struct
    .unnest("vc")                                              # flatten struct -> two columns
)

# Handle Polars version differences ("count" vs "counts")
count_col = "count" if "count" in vc_pl.columns else "counts"

polars_vc = (
    vc_pl.sort("season_type")
         .to_pandas()
         .set_index("season_type")[count_col]
)

# --- Pandas value counts ---
pdf = df_twofive.to_pandas()
pandas_vc = pdf["season_type"].value_counts(dropna=False).sort_index()

print("Value counts (Polars):")
print(polars_vc.sort_index())

print("\nValue counts (Pandas):")
print(pandas_vc)

# --- Null counts for key columns ---
cols = ["epa", "pass", "rush"]

# Polars null counts
polars_null_counts = (
    df_twofive
    .select([pl.col(c).is_null().sum().alias(c) for c in cols])
    .to_pandas()
    .iloc[0]
)

# Pandas null counts
pandas_null_counts = pdf[cols].isna().sum()

print("\nNull counts (Polars):")
print(polars_null_counts)

print("\nNull counts (Pandas):")
print(pandas_null_counts)

Value counts (Polars):
season_type
REG    16193
Name: count, dtype: uint32

Value counts (Pandas):
REG    16193
Name: season_type, dtype: int64

Null counts (Polars):
epa     188
pass      0
rush      0
Name: 0, dtype: uint32

Null counts (Pandas):
epa     188
pass      0
rush      0
dtype: int64

## Build Executor

In [8]:
# B. Count of rush-flag vs play_type==rush
diag = {
    "rows_total": df_twofive.height,
    "rush_flag_rows": df_twofive.filter(pl.col("rush") == 1).height if "rush" in df_twofive.columns else "no 'rush' col",
    "play_type_rush_rows": df_twofive.filter(pl.col("play_type").str.to_lowercase().str.strip_chars() == "rush").height
}
diag

{'rows_total': 16193, 'rush_flag_rows': 4510, 'play_type_rush_rows': 0}

In [9]:
ex = MetricsExecutor(df_twofive)
print('Executor ready.')

Executor ready.

## Tests Follow

#### EPA Per Play, Ranked

In [10]:
df_out, summary = ex.execute('ranked epa per play')
display(df_out.to_pandas())
print(summary)

    rank team  epa_per_play  plays
0      1  ind      0.168236    475
1      2  dal      0.154035    523
2      3   kc      0.121330    484
3      4   gb      0.120480    410
4      5  det      0.119429    476
5      6  buf      0.117892    502
6      7  was      0.097276    474
7      8  pit      0.092975    440
8      9  sea      0.078156    453
9     10   ne      0.067629    477
10    11  mia      0.065350    434
11    12   tb      0.049836    501
12    13  den      0.018935    502
13    14  ari      0.017162    497
14    15  hou      0.014451    384
15    16   sf      0.012467    529
16    17  phi      0.010534    469
17    18  jax      0.008143    516
18    19  car      0.007218    511
19    20  lac      0.006830    503
20    21   la      0.004293    474
21    22  bal      0.003713    445
22    23  chi     -0.011493    417
23    24  nyj     -0.013685    484
24    25  atl     -0.014954    426
25    26  nyg     -0.016258    516
26    27  cin     -0.035682    550
27    28  min     -0.043124    391
28    29   no     -0.087176    513
29    30   lv     -0.108130    473
30    31  cle     -0.145410    536
31    32  ten     -0.147587    475

Computed team-level offensive overall EPA/play. Rank 1 is highest (best) for offense. Includes a 'plays' column for sample size context.

#### Defensive EPA Per Play

In [11]:
df_out, summary = ex.execute('ranked defensive epa per play allowed')
display(df_out.to_pandas())
print(summary)

    rank team  epa_per_play  plays
0      1  hou     -0.147726    388
1      2  min     -0.095579    408
2      3  den     -0.064237    493
3      4   la     -0.060429    521
4      5  sea     -0.041448    519
5      6  jax     -0.030929    472
6      7  ind     -0.023216    482
7      8  atl     -0.020478    358
8      9  det     -0.011154    463
9     10  lac     -0.001603    474
10    11  cle      0.001712    463
11    12   ne      0.002627    468
12    13   sf      0.003119    477
13    14   lv      0.003672    476
14    15  ari      0.008646    513
15    16  phi      0.013639    500
16    17  was      0.021713    499
17    18   tb      0.023507    481
18    19   gb      0.025325    420
19    20  chi      0.025500    383
20    21   no      0.028067    489
21    22  nyg      0.034397    520
22    23  ten      0.039812    492
23    24  car      0.040294    444
24    25  pit      0.049519    528
25    26   kc      0.052711    451
26    27  buf      0.057495    456
27    28  nyj      0.107765    493
28    29  cin      0.119070    585
29    30  bal      0.120533    524
30    31  mia      0.161553    493
31    32  dal      0.162797    527

Computed team-level defensive overall EPA/play. Rank 1 is lowest (best) for defense. Includes a 'plays' column for sample size context.

#### Rushing EPA per play

In [12]:
df_out, summary = ex.execute('ranked rushing epa per play')
display(df_out.to_pandas())
print(summary)

    rank team  epa_per_play  plays
0      1  ind      0.089640    167
1      2  car      0.039933    159
2      3   kc      0.019889    120
3      4  dal      0.003088    140
4      5  buf      0.000591    159
5      6  phi     -0.001926    139
6      7   gb     -0.003847    140
7      8  mia     -0.008075    111
8      9  pit     -0.009222    134
9     10  cle     -0.020486    141
10    11  atl     -0.021750    148
11    12  cin     -0.031861    127
12    13  det     -0.035811    170
13    14  jax     -0.046867    149
14    15  was     -0.057439    140
15    16  lac     -0.071798    134
16    17  hou     -0.076065    123
17    18  nyg     -0.078672    159
18    19  den     -0.083525    149
19    20  min     -0.101817    110
20    21  bal     -0.122635    130
21    22  nyj     -0.124703    141
22    23   no     -0.131698    157
23    24   la     -0.136588    140
24    25   tb     -0.142073    150
25    26  chi     -0.153243    119
26    27   sf     -0.153710    151
27    28  ari     -0.155029    134
28    29  ten     -0.156078    114
29    30  sea     -0.188933    167
30    31   lv     -0.260123    153
31    32   ne     -0.292112    135

Computed team-level offensive rush EPA/play. Rank 1 is highest (best) for offense. Includes a 'plays' column for sample size context.

#### Offensive Success Rate

In [13]:
df_out, summary = ex.execute('offensive success rate')
display(df_out.to_pandas())
print(summary)

    rank team  success_rate  plays
0      1  ind      0.538136    475
1      2  det      0.522199    476
2      3   la      0.513859    474
3      4  was      0.510593    474
4      5   kc      0.506250    484
5      6   gb      0.501229    410
6      7   sf      0.500000    529
7      8  sea      0.495556    453
8      9  pit      0.495392    440
9     10  buf      0.493976    502
10    11  nyj      0.492754    484
11    12  dal      0.492308    523
12    13  bal      0.479730    445
13    14  car      0.478346    511
14    15   ne      0.472574    477
15    16  lac      0.471888    503
16    17  mia      0.468677    434
17    18  atl      0.468085    426
18    19  cin      0.467273    550
19    20   tb      0.464789    501
20    21   no      0.459883    513
21    22  min      0.458974    391
22    23  nyg      0.456311    516
23    24  phi      0.455914    469
24    25  jax      0.453125    516
25    26  ari      0.449393    497
26    27   lv      0.447761    473
27    28  chi      0.443099    417
28    29  den      0.442886    502
29    30  hou      0.442408    384
30    31  ten      0.417722    475
31    32  cle      0.399625    536

Computed team-level offensive overall success rate (share of plays marked successful; fallback is EPA>0). Rank 1 is highest for offense.

#### Defensive Success Rate

In [14]:
df_out, summary = ex.execute('defensive success rate')
display(df_out.to_pandas())
print(summary)

    rank team  success_rate  plays
0      1  den      0.414286    493
1      2  hou      0.420779    388
2      3  car      0.433107    444
3      4  min      0.433168    408
4      5  cle      0.434783    463
5      6   la      0.438462    521
6      7  sea      0.441860    519
7      8  nyj      0.444672    493
8      9  lac      0.448203    474
9     10  was      0.452525    499
10    11  ten      0.462012    492
11    12  det      0.463043    463
12    13  jax      0.468085    472
13    14   lv      0.468354    476
14    15   gb      0.468900    420
15    16  atl      0.474719    358
16    17  phi      0.475904    500
17    18   no      0.480412    489
18    19  ari      0.482353    513
19    20  nyg      0.483495    520
20    21   ne      0.483871    468
21    22  pit      0.490530    528
22    23   tb      0.492693    481
23    24  buf      0.493392    456
24    25   sf      0.504219    477
25    26   kc      0.507795    451
26    27  chi      0.507853    383
27    28  ind      0.509395    482
28    29  cin      0.512111    585
29    30  mia      0.512245    493
30    31  bal      0.512524    524
31    32  dal      0.517176    527

Computed team-level defensive overall success rate (share of plays marked successful; fallback is EPA>0). Rank 1 is lowest for defense.

## EPA Per Dropback

In [22]:

mex = MetricsExecutor(df_twofive)

# Run the query
out_df, summary = mex.execute("ranked offensive EPA per dropback")

# Print both to verify
print(out_df)
print(summary)

# Basic validation
assert isinstance(out_df, pl.DataFrame)
assert "epa_per_dropback" in out_df.columns
assert "dropbacks" in out_df.columns
assert out_df.height > 0, "No rows returned — filtering may have failed."

print("✅ EPA per dropback test passed.")

out_pd = out_df.to_pandas()
display(out_pd)

shape: (32, 4)
┌──────┬──────┬──────────────────┬───────────┐
│ rank ┆ team ┆ epa_per_dropback ┆ dropbacks │
│ ---  ┆ ---  ┆ ---              ┆ ---       │
│ u32  ┆ str  ┆ f32              ┆ u32       │
╞══════╪══════╪══════════════════╪═══════════╡
│ 1    ┆ sea  ┆ 0.317287         ┆ 173       │
│ 2    ┆ det  ┆ 0.316514         ┆ 187       │
│ 3    ┆ ne   ┆ 0.310361         ┆ 219       │
│ 4    ┆ gb   ┆ 0.309409         ┆ 166       │
│ 5    ┆ tb   ┆ 0.293293         ┆ 223       │
│ …    ┆ …    ┆ …                ┆ …         │
│ 28   ┆ lv   ┆ -0.056172        ┆ 209       │
│ 29   ┆ nyg  ┆ -0.068673        ┆ 236       │
│ 30   ┆ cin  ┆ -0.115053        ┆ 275       │
│ 31   ┆ ten  ┆ -0.254228        ┆ 234       │
│ 32   ┆ cle  ┆ -0.265621        ┆ 267       │
└──────┴──────┴──────────────────┴───────────┘
Computed team-level offensive EPA per dropback. Rank 1 is highest (best) for offense. Includes a 'dropbacks' column for sample size context.
✅ EPA per dropback test passed.

    rank team  epa_per_dropback  dropbacks
0      1  sea          0.317287        173
1      2  det          0.316514        187
2      3   ne          0.310361        219
3      4   gb          0.309409        166
4      5   tb          0.293293        223
5      6  dal          0.248971        247
6      7  ind          0.245834        201
7      8  buf          0.219069        218
8      9   kc          0.213900        250
9     10  was          0.191740        206
10    11   la          0.181288        220
11    12  pit          0.158264        189
12    13   sf          0.111104        259
13    14  chi          0.109158        188
14    15  den          0.103199        228
15    16  ari          0.088938        241
16    17  mia          0.085976        212
17    18  hou          0.084867        175
18    19  lac          0.037517        248
19    20  jax          0.037445        236
20    21  atl          0.021837        179
21    22  bal          0.009669        194
22    23  phi          0.005078        210
23    24   no         -0.014915        229
24    25  nyj         -0.034021        222
25    26  car         -0.034656        224
26    27  min         -0.047964        180
27    28   lv         -0.056172        209
28    29  nyg         -0.068673        236
29    30  cin         -0.115053        275
30    31  ten         -0.254228        234
31    32  cle         -0.265621        267

## Tiny Synthetic Unit Test (Deterministic)

In [ ]:
toy = pl.DataFrame({
    'posteam': ['A','A','B','B','C','C'],
    'defteam': ['X','Y','X','Y','X','Y'],
    'epa':     [0.2, -0.1, 0.05, 0.30, -0.20, 0.10],
    'play_type': ['pass','rush','pass','rush','pass','rush'],
    'pass':   [1,0,1,0,1,0],
    'rush':   [0,1,0,1,0,1],
})
ex_toy = MetricsExecutor(toy)

out, _ = ex_toy.execute('ranked epa per play')
vals = dict(zip(out['team'].to_list(), [round(x,3) for x in out['epa_per_play'].to_list()]))
assert vals == {'B': 0.175, 'A': 0.05, 'C': -0.05}, f"unexpected offense epa: {vals}"

out_d, _ = ex_toy.execute('ranked defensive epa per play allowed')
vals_d = dict(zip(out_d['team'].to_list(), [round(x,3) for x in out_d['epa_per_play'].to_list()]))
assert vals_d == {'X': 0.017, 'Y': 0.1}, f"unexpected defense epa: {vals_d}"

print('✓ Synthetic tests passed.')